import os
import pandas as pd
from google import genai
from dotenv import load_dotenv

load_dotenv()

# Get API Key from environment variable
API_KEY = os.getenv('GEMINI_API_KEY')

# Initialize the Gemini client
client = genai.Client(api_key=API_KEY)

# Function to generate quotes using Gemini
def generate_quotes():
    quotes = []

    # Request content from Gemini model
    response = client.models.generate_content(
        # model="gemini-2.0-flash",
        model="gemini-1.5-flash-latest",
        contents="Generate a motivational quote"
    )

    # Assuming response.text contains the quote generated by the model
    quote = response.text.strip()  # Clean any extra spaces or newline characters
    quotes.append({"Quote": quote})  # Store the quote
    
    return quotes

# Generate a list of quotes
quotes_data = generate_quotes()

# Convert to pandas DataFrame
df = pd.DataFrame(quotes_data)

# Save to CSV
df.to_csv('quotes.csv', index=False)

print("✅ Quotes saved to 'quotes.csv'")
